source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'8.0'
use_frameworks!

target 'ThreeLevelDirectoryDemo' do
   pod 'MJRefresh', '~>1.0.0'
   pod 'SDWebImage', '~>3.8'
   pod 'FMDB', '2.0'
   pod 'MBProgressHUD', '~>1.0'
   pod 'AFNetworking', '~>3.1.0'
end
